apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-dev

spec:
  source:
    repoURL: https://github.com/your-repo/devsecops-platform
    path: kubernetes/base
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
