apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-prod

spec:
  project: default

  source:
    repoURL: https://github.com/your-repo/devsecops-platform
    targetRevision: HEAD
    path: kubernetes/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
